# Generated by Django 2.2.12 on 2020-06-01 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=30)),
                ('job_description', models.CharField(max_length=30)),
                ('job_location', models.CharField(max_length=30)),
                ('company_name', models.CharField(max_length=30)),
                ('Designation', models.CharField(max_length=30)),
                ('qualification', models.CharField(max_length=30)),
                ('course', models.CharField(max_length=30)),
                ('specialization', models.CharField(max_length=30)),
                ('course_type', models.CharField(max_length=30)),
                ('passing_year', models.CharField(max_length=30)),
                ('experience', models.CharField(max_length=30)),
                ('salary', models.CharField(max_length=30)),
                ('industry', models.CharField(max_length=30)),
                ('skills', models.CharField(max_length=30)),
                ('job_category', models.CharField(max_length=30)),
                ('job_type', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField(max_length=8)),
                ('clocation', models.CharField(max_length=30)),
                ('qualification', models.CharField(max_length=30)),
                ('course', models.CharField(max_length=30)),
                ('specialization', models.CharField(max_length=30)),
                ('university', models.CharField(max_length=30)),
                ('College', models.CharField(max_length=30)),
                ('course_type', models.CharField(max_length=30)),
                ('passing_year', models.CharField(max_length=30)),
                ('experience', models.CharField(max_length=30)),
                ('cctc', models.CharField(max_length=30)),
                ('ectc', models.CharField(max_length=30)),
                ('industry', models.CharField(max_length=30)),
                ('skills', models.CharField(max_length=30)),
                ('job_category', models.CharField(max_length=30)),
                ('job_type', models.CharField(max_length=30)),
            ],
        ),
    ]
