# Generated by Django 2.2.12 on 2020-06-03 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_auto_20200602_1906'),
    ]

    operations = [
        migrations.CreateModel(
            name='guru',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avlanch', models.CharField(max_length=30)),
            ],
        ),
    ]
