# Generated by Django 2.2.12 on 2020-06-03 16:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portal', '0004_assignuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignuser',
            name='user',
        ),
        migrations.AddField(
            model_name='assignuser',
            name='user',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
