# Generated by Django 2.1.5 on 2020-06-10 10:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_auto_20200608_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='apply',
            field=models.ManyToManyField(null='True', related_name='applyjob', to=settings.AUTH_USER_MODEL),
        ),
    ]
