# Generated by Django 2.2.12 on 2020-06-03 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_auto_20200603_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignuser',
            name='assignrole',
            field=models.ManyToManyField(null=True, to='auth.Group'),
        ),
    ]
