# Generated by Django 2.2.12 on 2020-06-03 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_auto_20200603_2154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignuser',
            name='assignrole',
        ),
        migrations.RemoveField(
            model_name='assignuser',
            name='user',
        ),
        migrations.DeleteModel(
            name='guru',
        ),
        migrations.DeleteModel(
            name='AssignUser',
        ),
    ]
