# Generated by Django 2.2.12 on 2020-06-03 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_assignuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AssignUser',
        ),
    ]
