# Generated by Django 2.2.12 on 2020-06-04 05:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portal', '0010_assign'),
    ]

    operations = [
        migrations.AddField(
            model_name='assign',
            name='assign',
            field=models.ManyToManyField(null=True, related_name='assignrole', to=settings.AUTH_USER_MODEL),
        ),
    ]
