# Generated by Django 2.2.12 on 2020-06-04 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0011_assign_assign'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assign',
            old_name='assign',
            new_name='user',
        ),
    ]
