# Generated by Django 2.2.12 on 2020-06-04 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0014_auto_20200604_1703'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groups',
            old_name='group',
            new_name='groups',
        ),
        migrations.RenameField(
            model_name='groups',
            old_name='user',
            new_name='users',
        ),
    ]
