# Generated by Django 2.2.12 on 2020-06-04 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0015_auto_20200604_1705'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Groups',
        ),
    ]
